using ArgoBooks.Core.Data;
using ArgoBooks.Core.Enums;
using ArgoBooks.Core.Models.Entities;
using ArgoBooks.Core.Models.Inventory;
using ArgoBooks.Core.Services;
using Xunit;

namespace ArgoBooks.Tests.Services;

/// <summary>
/// Receiving a purchase order moves stock through InventoryStockService like every other stock
/// movement (docs/Calculations.md §14): the units go to the product's first stock record, or a new
/// one costed from the order line in USD, and each record gets one adjustment for what it received.
/// </summary>
public class PurchaseOrderReceivingTests
{
    private static CompanyData Company()
    {
        var data = new CompanyData();
        data.Settings.Localization.Currency = "USD";
        data.Locations.Add(new Location { Id = "LOC-001", Name = "Warehouse" });
        data.Locations.Add(new Location { Id = "LOC-002", Name = "Shop" });
        data.Products.Add(new Product { Id = "PRD-001", Name = "Flour", TrackInventory = true, CostPrice = 5m });
        return data;
    }

    private static PurchaseOrder EuroOrder(decimal quantity, decimal unitCost) => new()
    {
        Id = "PO-00001",
        PoNumber = "#PO-2026-001",
        OrderDate = new DateTime(2026, 3, 1),
        OriginalCurrency = "EUR",
        Total = 200m,
        TotalUSD = 250m,
        LineItems = [new PurchaseOrderLineItem { ProductId = "PRD-001", Quantity = quantity, UnitCost = unitCost }]
    };

    [Fact]
    public void ANewStockRecord_IsCostedFromTheOrderLineInUsd_AtTheFirstLocation()
    {
        var data = Company();
        var order = EuroOrder(quantity: 8, unitCost: 10m);

        var changes = InventoryStockService.ReceivePurchaseOrder(data, order, [(order.LineItems[0], 8m)]);

        var item = Assert.Single(data.Inventory);
        Assert.Equal(8, item.InStock);
        Assert.Equal(12.5m, item.UnitCost); // 10 EUR at the order's 1.25 USD per EUR
        Assert.Equal("LOC-001", item.LocationId);
        Assert.True(Assert.Single(changes).WasCreated);

        var adjustment = Assert.Single(data.StockAdjustments);
        Assert.Equal(item.Id, adjustment.InventoryItemId);
        Assert.Equal(AdjustmentType.Add, adjustment.AdjustmentType);
        Assert.Equal(8, adjustment.Quantity);
        Assert.Equal(0, adjustment.PreviousStock);
        Assert.Equal(8, adjustment.NewStock);
        Assert.Equal("#PO-2026-001", adjustment.ReferenceNumber);
        Assert.True(adjustment.IsAutoGenerated);
    }

    [Fact]
    public void AnOrderStillWaitingForItsRate_LeavesTheNewRecordAtTheCostPrice()
    {
        var data = Company();
        var order = EuroOrder(quantity: 2, unitCost: 10m);
        order.IsPendingConversion = true;

        InventoryStockService.ReceivePurchaseOrder(data, order, [(order.LineItems[0], 2m)]);

        Assert.Equal(5m, Assert.Single(data.Inventory).UnitCost);
    }

    [Fact]
    public void ReceivingIntoAnExistingRecord_AddsToItAndKeepsItsCost()
    {
        var data = Company();
        var existing = new InventoryItem { Id = "INV-ITM-00001", ProductId = "PRD-001", LocationId = "LOC-002", InStock = 3, UnitCost = 4m };
        data.Inventory.Add(existing);
        var order = EuroOrder(quantity: 5, unitCost: 10m);

        InventoryStockService.ReceivePurchaseOrder(data, order, [(order.LineItems[0], 5m)]);

        Assert.Same(existing, Assert.Single(data.Inventory));
        Assert.Equal(8, existing.InStock);
        Assert.Equal(4m, existing.UnitCost);
        Assert.Equal("LOC-002", existing.LocationId);
        var adjustment = Assert.Single(data.StockAdjustments);
        Assert.Equal((3m, 8m, 5m), (adjustment.PreviousStock, adjustment.NewStock, adjustment.Quantity));
    }

    [Fact]
    public void AnUntrackedProductWithNoStockRecord_MovesNothing()
    {
        var data = Company();
        data.Products[0].TrackInventory = false;
        var order = EuroOrder(quantity: 5, unitCost: 10m);

        var changes = InventoryStockService.ReceivePurchaseOrder(data, order, [(order.LineItems[0], 5m)]);

        Assert.Empty(changes);
        Assert.Empty(data.Inventory);
        Assert.Empty(data.StockAdjustments);
    }

    [Fact]
    public void Revert_PutsStockBackAndRemovesWhatReceivingAdded()
    {
        var data = Company();
        var existing = new InventoryItem { Id = "INV-ITM-00001", ProductId = "PRD-001", LocationId = "LOC-001", InStock = 3, UnitCost = 4m };
        data.Inventory.Add(existing);
        data.Products.Add(new Product { Id = "PRD-002", Name = "Sugar", TrackInventory = true });
        var order = EuroOrder(quantity: 5, unitCost: 10m);
        order.LineItems.Add(new PurchaseOrderLineItem { ProductId = "PRD-002", Quantity = 4, UnitCost = 2m });

        var changes = InventoryStockService.ReceivePurchaseOrder(data, order,
            [(order.LineItems[0], 5m), (order.LineItems[1], 4m)]);
        Assert.Equal(2, data.Inventory.Count);
        Assert.Equal(2, data.StockAdjustments.Count);

        InventoryStockService.Revert(data, changes);

        Assert.Same(existing, Assert.Single(data.Inventory));
        Assert.Equal(3, existing.InStock);
        Assert.Empty(data.StockAdjustments);
    }
}
