using ArgoBooks.Core.Data;
using ArgoBooks.Core.Enums;
using ArgoBooks.Core.Models.Common;
using ArgoBooks.Core.Models.Entities;
using ArgoBooks.Core.Models.Inventory;
using ArgoBooks.Core.Models.Transactions;

namespace ArgoBooks.Core.Services;

/// <summary>
/// Moves stock when a purchase, sale or transfer is saved or a purchase order is received, and
/// fixes what sold stock cost at the moment of the sale. The forms and the imports all go through
/// here so they move stock the same way. See docs/Calculations.md §14.
/// </summary>
public static class InventoryStockService
{
    /// <summary>
    /// The location stock belongs to when the caller names none: the company's first location, or a
    /// real one created for it. Every stock row points at a location that exists on the Locations page.
    /// </summary>
    public static string EnsureLocationId(CompanyData data)
    {
        var existing = data.Locations.FirstOrDefault();
        if (existing != null)
            return existing.Id;

        var location = new Location { Id = new IdGenerator(data).NextLocationId(), Name = "Main" };
        data.Locations.Add(location);
        return location.Id;
    }

    /// <summary>
    /// Applies a newly saved purchase or sale to stock. Only lines whose product tracks inventory
    /// move stock.
    /// </summary>
    public static List<StockChange> Apply(
        CompanyData data, IReadOnlyList<LineItem> lines, Transaction transaction, bool isPurchase) =>
        ApplyEdit(data, [], lines, transaction, isPurchase, isPurchase ? "Expense transaction" : "Revenue transaction");

    /// <summary>
    /// Replaces what <paramref name="oldLines"/> did to stock with what <paramref name="newLines"/>
    /// do, recording one adjustment per stock record for the net change. Pass no new lines to undo a
    /// deleted transaction's stock.
    /// </summary>
    public static List<StockChange> ApplyEdit(
        CompanyData data, IReadOnlyList<LineItem> oldLines, IReadOnlyList<LineItem> newLines,
        Transaction transaction, bool isPurchase, string reason)
    {
        var touched = new List<StockChange.Builder>();
        var byItem = new Dictionary<InventoryItem, StockChange.Builder>();
        var costPriceChanged = new HashSet<Product>();

        StockChange.Builder Track(InventoryItem item, Product product, bool wasCreated)
        {
            if (!byItem.TryGetValue(item, out var builder))
            {
                builder = new StockChange.Builder(data, item, product, wasCreated);
                byItem[item] = builder;
                touched.Add(builder);
            }
            return builder;
        }

        // Give back what the transaction actually moved, before the new lines take anything. Its own
        // adjustments say how much: a line saved before its product tracked stock, before 2.0.6, or by
        // the spreadsheet import moved nothing, and taking its quantity back would leave stock short.
        var moved = data.StockAdjustments
            .Where(a => a.IsAutoGenerated && a.ReferenceNumber == transaction.Id)
            .GroupBy(a => a.InventoryItemId)
            .Select(g => (ItemId: g.Key, Units: g.Sum(a => a.AdjustmentType == AdjustmentType.Add ? a.Quantity : -a.Quantity)))
            .Where(m => m.Units != 0)
            .ToList();
        foreach (var (itemId, units) in moved)
        {
            var item = data.Inventory.FirstOrDefault(i => i.Id == itemId);
            var product = item == null ? null : data.GetProduct(item.ProductId);
            if (item == null || product == null) continue;

            Track(item, product, wasCreated: false);
            item.InStock -= units;
        }

        foreach (var line in oldLines.Where(l => l.OpeningUnitsUsed != 0))
        {
            var product = TrackedProduct(data, line);
            var item = product == null ? null : FindStockItem(data, product.Id, line.LocationId);
            if (item == null) continue;

            Track(item, product!, wasCreated: false);
            item.OpeningUnits += line.OpeningUnitsUsed;
        }

        var usdPerNative = UsdPerNative(transaction);
        var currency = OriginalCurrency(transaction);
        var inCompanyCurrency = string.Equals(currency, data.Settings.Localization.Currency, StringComparison.OrdinalIgnoreCase);

        // A purchase or sale saved before cost of goods sold began was expensed, or sold at no cost, and
        // its stock is part of the opening units. Editing it moves stock as before and nothing more, or
        // that stock would come off profit twice.
        var savedBeforeCostOfGoods =
            moved.Count > 0 &&
            !oldLines.Any(l => l.IsStockPurchase || l.CostOfGoodsUSD != null);

        // An edited sale keeps the unit cost it was saved at, so a later purchase that changed the
        // stock's cost doesn't rewrite its past profit. Only a product the edit adds takes today's cost.
        // A line whose cost was still pending has no saved cost to keep.
        var savedUnitCost = oldLines
                .Where(l => !isPurchase && l.CostOfGoodsUSD != null && !l.IsCostOfGoodsPending && l.ProductId != null && l.Quantity - l.OpeningUnitsUsed > 0)
                .GroupBy(l => (l.ProductId, l.LocationId))
                .ToDictionary(g => g.Key, g => g.Sum(l => l.CostOfGoodsUSD!.Value) / g.Sum(l => l.Quantity - l.OpeningUnitsUsed));

        foreach (var line in newLines)
        {
            line.CostOfGoodsUSD = null;
            line.IsCostOfGoodsPending = false;
            line.OpeningUnitsUsed = 0;
            line.IsStockPurchase = false;

            var product = TrackedProduct(data, line);
            if (product == null || line.Quantity == 0) continue;

            var item = FindStockItem(data, product.Id, line.LocationId);
            var builder = item == null
                ? Track(item = CreateStockItem(data, product, line.LocationId, transaction.Date), product, wasCreated: true)
                : Track(item, product, wasCreated: false);
            line.LocationId = item.LocationId;

            if (isPurchase)
            {
                item.InStock += line.Quantity;
                if (savedBeforeCostOfGoods) continue;
                line.IsStockPurchase = true;

                if (line.Quantity > 0)
                    SetUnitCost(data, item, line.Subtotal / line.Quantity, currency, transaction.Date, usdPerNative);

                if (inCompanyCurrency && costPriceChanged.Add(product))
                {
                    builder.RecordCostPrice(product);
                    product.CostPrice = line.UnitPrice;
                }
            }
            else if (savedBeforeCostOfGoods)
            {
                item.InStock -= line.Quantity;
            }
            else
            {
                var openingUsed = line.Quantity > 0 ? Math.Min(Math.Max(item.OpeningUnits, 0), line.Quantity) : 0;
                item.OpeningUnits -= openingUsed;
                line.OpeningUnitsUsed = openingUsed;
                var costedUnits = line.Quantity - openingUsed;
                if (savedUnitCost.TryGetValue((product.Id, item.LocationId), out var saved))
                {
                    line.CostOfGoodsUSD = costedUnits * saved;
                }
                else
                {
                    line.IsCostOfGoodsPending = item.IsPendingConversion && costedUnits != 0;
                    line.CostOfGoodsUSD = costedUnits * item.UnitCost;
                }
                item.InStock -= line.Quantity;
            }
        }

        return RecordAdjustments(data, touched, reason, transaction.Id);
    }

    /// <summary>
    /// Adds a purchase order's received units to stock. Each line goes to its product's first stock
    /// record; a tracked product with none gets one at the company's first location, costed from the
    /// order line at the order's own rate, or pending while the order waits for that rate.
    /// Receiving into an existing record leaves its cost as it is.
    /// </summary>
    public static List<StockChange> ReceivePurchaseOrder(
        CompanyData data, PurchaseOrder order, IReadOnlyList<(PurchaseOrderLineItem Line, decimal Quantity)> received)
    {
        var touched = new List<StockChange.Builder>();
        var byItem = new Dictionary<InventoryItem, StockChange.Builder>();

        foreach (var (line, quantity) in received)
        {
            if (quantity <= 0) continue;

            var product = data.GetProduct(line.ProductId);
            var item = FindStockItem(data, line.ProductId, null);
            if (item == null)
            {
                if (product is not { TrackInventory: true }) continue;

                item = CreateStockItem(data, product, null, order.OrderDate);
                SetUnitCost(data, item, line.UnitCost, OrderCurrency(order), order.OrderDate, UsdPerNative(order));
                byItem[item] = new StockChange.Builder(data, item, product, wasCreated: true);
                touched.Add(byItem[item]);
            }
            else if (!byItem.ContainsKey(item))
            {
                byItem[item] = new StockChange.Builder(data, item, product, wasCreated: false);
                touched.Add(byItem[item]);
            }

            item.InStock += quantity;
        }

        return RecordAdjustments(data, touched, "Purchase order received", order.PoNumber);
    }

    /// <summary>
    /// Finishes a stock move: refreshes each touched record's status and records one adjustment per
    /// record for its net change.
    /// </summary>
    private static List<StockChange> RecordAdjustments(
        CompanyData data, List<StockChange.Builder> touched, string reason, string reference)
    {
        var changes = new List<StockChange>(touched.Count);
        HashSet<string>? takenIds = null;
        foreach (var builder in touched)
        {
            var item = builder.Item;
            item.Status = item.CalculateStatus();
            item.LastUpdated = DateTime.UtcNow;

            var net = item.InStock - builder.OldStock;
            StockAdjustment? adjustment = null;
            if (net != 0)
            {
                adjustment = new StockAdjustment
                {
                    Id = new IdGenerator(data).NextStockAdjustmentId(
                        takenIds ??= IdGenerator.TakenSet(data.StockAdjustments.Select(a => a.Id))),
                    InventoryItemId = item.Id,
                    AdjustmentType = net > 0 ? AdjustmentType.Add : AdjustmentType.Remove,
                    Quantity = Math.Abs(net),
                    PreviousStock = builder.OldStock,
                    NewStock = item.InStock,
                    Reason = reason,
                    ReferenceNumber = reference,
                    Timestamp = DateTime.UtcNow,
                    IsAutoGenerated = true
                };
                data.StockAdjustments.Add(adjustment);
            }

            changes.Add(builder.Build(adjustment));
        }

        return changes;
    }

    /// <summary>
    /// Puts stock back as it was before <paramref name="changes"/>: stock, opening units, unit cost and
    /// cost price restored, adjustments removed, and stock records the change created removed. A cost
    /// that was pending then and has converted since comes back converted rather than pending again.
    /// </summary>
    public static void Revert(CompanyData data, IReadOnlyList<StockChange> changes)
    {
        for (var i = changes.Count - 1; i >= 0; i--)
        {
            var change = changes[i];
            var item = change.Item;
            var convertedRate = change.OldPendingCost?.ConvertedRate;
            item.InStock = change.OldStock;
            item.OpeningUnits = change.OldOpeningUnits;
            item.UnitCost = change.OldCostPending && convertedRate is { } rate
                ? change.OldPendingCost!.Total * rate
                : change.OldUnitCost;
            item.IsPendingConversion = change.OldCostPending && convertedRate == null;
            item.Status = item.CalculateStatus();
            item.LastUpdated = DateTime.UtcNow;

            if (change.CostPriceProduct != null)
                change.CostPriceProduct.CostPrice = change.OldCostPrice;

            if (change.Adjustment != null)
                data.StockAdjustments.Remove(change.Adjustment);

            if (change.WasCreated)
                data.Inventory.Remove(item);

            var entry = change.WasCreated || convertedRate != null ? null : change.OldPendingCost;
            if (!ReferenceEquals(PendingCostEntry(data, item.Id), entry))
                UsdConversion.Set(data, UsdConversion.KeyOf(item), entry);
        }
    }

    /// <summary>
    /// The stock record a line takes from or adds to: the one at the line's location when it has one,
    /// otherwise the product's first.
    /// </summary>
    public static InventoryItem? FindStockItem(CompanyData data, string productId, string? locationId)
    {
        if (!string.IsNullOrEmpty(locationId))
        {
            var atLocation = data.Inventory.FirstOrDefault(i => i.ProductId == productId && i.LocationId == locationId);
            if (atLocation != null)
                return atLocation;
        }

        return data.Inventory.FirstOrDefault(i => i.ProductId == productId);
    }

    /// <summary>Stock records for a product, one per location it is stocked at.</summary>
    public static List<InventoryItem> StockItemsFor(CompanyData data, string productId) =>
        data.Inventory.Where(i => i.ProductId == productId).ToList();

    /// <summary>
    /// Moves stock from one location to another, recording the transfer and a matching adjustment at
    /// each end. Opening units move in proportion, so the stock keeps its cost basis.
    /// </summary>
    public static StockTransferResult Transfer(
        CompanyData data, InventoryItem source, string destinationLocationId, decimal quantity, string notes)
    {
        if (quantity <= 0)
            throw new ArgumentOutOfRangeException(nameof(quantity), "A transfer moves a positive quantity.");
        if (source.LocationId == destinationLocationId)
            throw new ArgumentException("A transfer needs a different destination.", nameof(destinationLocationId));

        var product = data.GetProduct(source.ProductId);
        var destination = data.Inventory.FirstOrDefault(i =>
            i.ProductId == source.ProductId && i.LocationId == destinationLocationId);
        var destinationCreated = destination == null;
        if (destination == null)
        {
            destination = product != null
                ? CreateStockItem(data, product, destinationLocationId, DateTime.Today)
                : CreateStockItem(data, source, destinationLocationId);
            destination.UnitCost = source.UnitCost;
            destination.IsPendingConversion = source.IsPendingConversion;
            var sourceCost = source.IsPendingConversion ? PendingCostEntry(data, source.Id) : null;
            UsdConversion.Set(data, UsdConversion.KeyOf(destination), sourceCost == null
                ? null
                : PendingCostFor(destination, sourceCost.Total, sourceCost.OriginalCurrency, sourceCost.TransactionDate));
        }

        var result = new StockTransferResult
        {
            Source = source,
            Destination = destination,
            DestinationCreated = destinationCreated,
            SourceOldStock = source.InStock,
            SourceOldOpeningUnits = source.OpeningUnits,
            DestinationOldStock = destination.InStock,
            DestinationOldOpeningUnits = destination.OpeningUnits
        };

        var openingMoved = source.InStock > 0
            ? Math.Min(source.OpeningUnits, source.OpeningUnits * quantity / source.InStock)
            : 0;
        openingMoved = Math.Max(openingMoved, 0);

        source.InStock -= quantity;
        source.OpeningUnits -= openingMoved;
        destination.InStock += quantity;
        destination.OpeningUnits += openingMoved;

        foreach (var item in new[] { source, destination })
        {
            item.Status = item.CalculateStatus();
            item.LastUpdated = DateTime.UtcNow;
        }

        var transfer = new StockTransfer
        {
            Id = new IdGenerator(data).NextStockTransferId(),
            InventoryItemId = source.Id,
            SourceLocationId = source.LocationId,
            DestinationLocationId = destinationLocationId,
            Quantity = quantity,
            TransferDate = DateTime.Now,
            Status = TransferStatus.Completed,
            Notes = notes,
            CreatedAt = DateTime.UtcNow,
            CompletedAt = DateTime.UtcNow
        };
        data.StockTransfers.Add(transfer);

        var sourceName = data.GetLocation(source.LocationId)?.Name ?? source.LocationId;
        var destinationName = data.GetLocation(destinationLocationId)?.Name ?? destinationLocationId;

        var outAdjustment = new StockAdjustment
        {
            Id = new IdGenerator(data).NextStockAdjustmentId(),
            InventoryItemId = source.Id,
            AdjustmentType = AdjustmentType.Remove,
            Quantity = quantity,
            PreviousStock = result.SourceOldStock,
            NewStock = source.InStock,
            Reason = $"Transfer to {destinationName}",
            ReferenceNumber = transfer.Id,
            Timestamp = DateTime.UtcNow,
            IsAutoGenerated = true
        };
        data.StockAdjustments.Add(outAdjustment);

        var inAdjustment = new StockAdjustment
        {
            Id = new IdGenerator(data).NextStockAdjustmentId(),
            InventoryItemId = destination.Id,
            AdjustmentType = AdjustmentType.Add,
            Quantity = quantity,
            PreviousStock = result.DestinationOldStock,
            NewStock = destination.InStock,
            Reason = $"Transfer from {sourceName}",
            ReferenceNumber = transfer.Id,
            Timestamp = DateTime.UtcNow,
            IsAutoGenerated = true
        };
        data.StockAdjustments.Add(inAdjustment);

        result.Transfer = transfer;
        result.OutAdjustment = outAdjustment;
        result.InAdjustment = inAdjustment;
        return result;
    }

    public static void RevertTransfer(CompanyData data, StockTransferResult result)
    {
        result.Source.InStock = result.SourceOldStock;
        result.Source.OpeningUnits = result.SourceOldOpeningUnits;
        result.Destination.InStock = result.DestinationOldStock;
        result.Destination.OpeningUnits = result.DestinationOldOpeningUnits;

        foreach (var item in new[] { result.Source, result.Destination })
        {
            item.Status = item.CalculateStatus();
            item.LastUpdated = DateTime.UtcNow;
        }

        data.StockAdjustments.Remove(result.OutAdjustment);
        data.StockAdjustments.Remove(result.InAdjustment);
        data.StockTransfers.Remove(result.Transfer);

        if (result.DestinationCreated)
        {
            data.Inventory.Remove(result.Destination);
            UsdConversion.Set(data, UsdConversion.KeyOf(result.Destination), null);
        }
    }

    /// <summary>
    /// USD per unit of the transaction's own currency, or null while its rate is not known yet, in
    /// which case a purchase leaves the stock's unit cost pending.
    /// </summary>
    public static decimal? UsdPerNative(Transaction transaction) =>
        UsdPerNative(OriginalCurrency(transaction), transaction.Total, transaction.TotalUSD, transaction.IsPendingConversion);

    /// <summary><see cref="UsdPerNative(Transaction)"/> for a purchase order, whose line costs are in its own currency.</summary>
    public static decimal? UsdPerNative(PurchaseOrder order) =>
        UsdPerNative(OrderCurrency(order), order.Total, order.TotalUSD, order.IsPendingConversion);

    private static decimal? UsdPerNative(string currency, decimal total, decimal totalUSD, bool isPending)
    {
        if (string.Equals(currency, "USD", StringComparison.OrdinalIgnoreCase))
            return 1m;
        if (isPending || total == 0 || totalUSD == 0)
            return null;
        return totalUSD / total;
    }

    /// <summary>
    /// The product's cost price, which is in the company's currency, in USD at <paramref name="date"/>'s
    /// rate. False while that rate isn't available.
    /// </summary>
    public static bool TryCostPriceUSD(CompanyData data, Product product, DateTime date, out decimal usd)
    {
        if (UnitCostUSD(product.CostPrice, CompanyCurrency(data), date, null) is { } known)
        {
            usd = known;
            return true;
        }

        usd = 0;
        return false;
    }

    /// <summary>
    /// Starts a new stock record at the product's cost price as of <paramref name="date"/>, or leaves
    /// its cost pending until that day's rate can be had (docs/Calculations.md §14).
    /// </summary>
    public static void StartAtCostPrice(CompanyData data, InventoryItem item, Product product, DateTime date) =>
        SetUnitCost(data, item, product.CostPrice, CompanyCurrency(data), date, null);

    /// <summary>
    /// A new stock record for <paramref name="product"/>, added to the company, starting at the
    /// product's cost price as of <paramref name="costDate"/>.
    /// </summary>
    public static InventoryItem CreateStockItem(CompanyData data, Product product, string? locationId, DateTime costDate)
    {
        var item = NewStockItem(data, product.Id, product.Sku, locationId);
        item.UnitOfMeasure = product.UnitOfMeasure;
        item.ReorderPoint = product.ReorderPoint;
        item.OverstockThreshold = product.OverstockThreshold;
        StartAtCostPrice(data, item, product, costDate);
        item.Status = item.CalculateStatus();
        return item;
    }

    /// <summary>
    /// Sets a stock record's unit cost from a cost in <paramref name="currency"/>. When the rate isn't
    /// available yet, the cost waits in the conversion queue and counts as 0 until
    /// <see cref="ApplyConvertedCost"/> fills it in, the way every other amount waits for its rate.
    /// </summary>
    private static void SetUnitCost(
        CompanyData data, InventoryItem item, decimal nativeUnitCost, string currency, DateTime date, decimal? usdPerNative)
    {
        if (UnitCostUSD(nativeUnitCost, currency, date, usdPerNative) is { } usd)
        {
            SetKnownCost(data, item, usd);
            return;
        }

        item.UnitCost = 0;
        item.IsPendingConversion = true;
        UsdConversion.Set(data, UsdConversion.KeyOf(item), PendingCostFor(item, nativeUnitCost, currency, date));
    }

    /// <summary>
    /// Gives a stock record a cost known in USD. A pending cost's queue entry stays while sales made
    /// during the wait still need the cost the stock had then.
    /// </summary>
    private static void SetKnownCost(CompanyData data, InventoryItem item, decimal usd)
    {
        item.UnitCost = usd;
        item.IsPendingConversion = false;
        if (!PendingCostLines(data, item).Any())
            UsdConversion.Set(data, UsdConversion.KeyOf(item), null);
    }

    private static decimal? UnitCostUSD(decimal nativeUnitCost, string currency, DateTime date, decimal? usdPerNative)
    {
        if (nativeUnitCost == 0 || string.Equals(currency, "USD", StringComparison.OrdinalIgnoreCase))
            return nativeUnitCost;
        return (usdPerNative ?? UsdConversion.CachedRate(currency, date)) is { } rate
            ? nativeUnitCost * rate
            : null;
    }

    /// <summary>
    /// Adds or updates a stock record from an import row. Both spreadsheet imports come through here.
    /// A record being updated changes only the fields in <paramref name="fields"/> (its JSON property
    /// names); a new one takes every field. The sheet's Unit Cost is the stored USD value, and a
    /// pending cost exports as 0, so only a different, non-zero cost replaces a pending one. Sales
    /// waiting on a record's pending cost find it by product and location, so those two are left as
    /// they are on such a record. See docs/Calculations.md §14.
    /// </summary>
    /// <returns>True when the record was created.</returns>
    public static bool ImportStockRecord(CompanyData data, InventoryItem row, IReadOnlySet<string> fields)
    {
        var item = data.Inventory.FirstOrDefault(i => i.Id == row.Id);
        var created = item == null;
        item ??= new InventoryItem { Id = row.Id };
        bool Has(string field) => created || fields.Contains(field);

        var costWaiting = !created && PendingCostLines(data, item).Any();
        if (Has("productId") && !costWaiting)
            item.ProductId = row.ProductId;
        if (Has("locationId") && !costWaiting)
            item.LocationId = row.LocationId;
        if (Has("sku"))
            item.Sku = row.Sku;
        if (Has("inStock"))
            item.InStock = row.InStock;
        if (Has("reserved"))
            item.Reserved = row.Reserved;
        if (Has("reorderPoint"))
            item.ReorderPoint = row.ReorderPoint;
        if (Has("overstockThreshold"))
            item.OverstockThreshold = row.OverstockThreshold;
        if (Has("unitOfMeasure") && !string.IsNullOrEmpty(row.UnitOfMeasure))
            item.UnitOfMeasure = row.UnitOfMeasure;
        if (Has("unitCost") && (created || !item.IsPendingConversion || row.UnitCost != 0))
            SetKnownCost(data, item, row.UnitCost);
        if (Has("lastUpdated"))
            item.LastUpdated = row.LastUpdated == DateTime.MinValue ? DateTime.UtcNow : row.LastUpdated;
        item.Status = item.CalculateStatus();

        if (created)
            data.Inventory.Add(item);
        return created;
    }

    /// <summary>
    /// Fills in a stock record's cost once its rate has come in: the record takes it unless a later
    /// purchase has already set a known cost, and every sale line that took this stock while its cost
    /// was pending gets its cost of goods sold from it. Called by the conversion queue.
    /// </summary>
    public static void ApplyConvertedCost(CompanyData data, PendingConversion entry, decimal rate)
    {
        var item = data.Inventory.FirstOrDefault(i => i.Id == entry.TransactionId);
        if (item == null) return;

        var unitCost = entry.Total * rate;
        if (item.IsPendingConversion)
        {
            item.UnitCost = unitCost;
            item.IsPendingConversion = false;
        }

        foreach (var line in PendingCostLines(data, item).ToList())
        {
            line.CostOfGoodsUSD = (line.Quantity - line.OpeningUnitsUsed) * unitCost;
            line.IsCostOfGoodsPending = false;
        }
    }

    /// <summary>
    /// Whether a stock record's queued cost has nothing left waiting on it: the record's cost is known
    /// and no sale line is waiting for it. False when the record no longer exists.
    /// </summary>
    public static bool IsCostSettled(CompanyData data, string itemId) =>
        data.Inventory.FirstOrDefault(i => i.Id == itemId) is { IsPendingConversion: false } item
        && !PendingCostLines(data, item).Any();

    private static IEnumerable<LineItem> PendingCostLines(CompanyData data, InventoryItem item) =>
        data.Revenues
            .SelectMany(r => r.LineItems)
            .Where(l => l.IsCostOfGoodsPending && l.ProductId == item.ProductId && l.LocationId == item.LocationId);

    private static PendingConversion PendingCostFor(InventoryItem item, decimal nativeUnitCost, string currency, DateTime date) => new()
    {
        TransactionId = item.Id,
        TransactionType = PendingConversionType.InventoryItem,
        OriginalCurrency = currency,
        TransactionDate = date,
        Total = nativeUnitCost
    };

    private static PendingConversion? PendingCostEntry(CompanyData data, string itemId) =>
        UsdConversion.Queued(data, new PendingConversionKey(itemId, PendingConversionType.InventoryItem));

    private static string CompanyCurrency(CompanyData data) =>
        string.IsNullOrEmpty(data.Settings.Localization.Currency) ? "USD" : data.Settings.Localization.Currency;

    private static string OrderCurrency(PurchaseOrder order) =>
        string.IsNullOrEmpty(order.OriginalCurrency) ? "USD" : order.OriginalCurrency;

    private static string OriginalCurrency(Transaction transaction) =>
        string.IsNullOrEmpty(transaction.OriginalCurrency) ? "USD" : transaction.OriginalCurrency;

    private static Product? TrackedProduct(CompanyData data, LineItem line)
    {
        if (string.IsNullOrEmpty(line.ProductId)) return null;
        var product = data.GetProduct(line.ProductId);
        return product is { TrackInventory: true } ? product : null;
    }

    private static InventoryItem CreateStockItem(CompanyData data, InventoryItem like, string locationId)
    {
        var item = NewStockItem(data, like.ProductId, like.Sku, locationId);
        item.UnitOfMeasure = like.UnitOfMeasure;
        item.ReorderPoint = like.ReorderPoint;
        item.OverstockThreshold = like.OverstockThreshold;
        item.Status = item.CalculateStatus();
        return item;
    }

    private static InventoryItem NewStockItem(CompanyData data, string productId, string sku, string? locationId)
    {
        var item = new InventoryItem
        {
            Id = new IdGenerator(data).NextInventoryItemId(),
            ProductId = productId,
            Sku = sku,
            LocationId = !string.IsNullOrEmpty(locationId)
                ? locationId
                : EnsureLocationId(data),
            LastUpdated = DateTime.UtcNow
        };
        data.Inventory.Add(item);
        return item;
    }
}

/// <summary>What one save did to one stock record, kept so the save can be undone.</summary>
public sealed class StockChange
{
    public required InventoryItem Item { get; init; }
    public required string ProductName { get; init; }
    public decimal OldStock { get; init; }
    public decimal NewStock { get; init; }
    public decimal OldOpeningUnits { get; init; }
    public decimal OldUnitCost { get; init; }
    public bool OldCostPending { get; init; }
    public PendingConversion? OldPendingCost { get; init; }
    public Product? CostPriceProduct { get; init; }
    public decimal OldCostPrice { get; init; }
    public StockAdjustment? Adjustment { get; init; }
    public bool WasCreated { get; init; }

    internal sealed class Builder(CompanyData data, InventoryItem item, Product? product, bool wasCreated)
    {
        public InventoryItem Item { get; } = item;
        public decimal OldStock { get; } = item.InStock;
        private readonly decimal _oldOpeningUnits = item.OpeningUnits;
        private readonly decimal _oldUnitCost = item.UnitCost;
        private readonly bool _oldCostPending = item.IsPendingConversion;
        private readonly PendingConversion? _oldPendingCost = UsdConversion.Queued(data, UsdConversion.KeyOf(item));
        private Product? _costPriceProduct;
        private decimal _oldCostPrice;

        public void RecordCostPrice(Product costProduct)
        {
            _costPriceProduct = costProduct;
            _oldCostPrice = costProduct.CostPrice;
        }

        public StockChange Build(StockAdjustment? adjustment) => new()
        {
            Item = Item,
            ProductName = product?.Name ?? string.Empty,
            OldStock = OldStock,
            NewStock = Item.InStock,
            OldOpeningUnits = _oldOpeningUnits,
            OldUnitCost = _oldUnitCost,
            OldCostPending = _oldCostPending,
            OldPendingCost = _oldPendingCost,
            CostPriceProduct = _costPriceProduct,
            OldCostPrice = _oldCostPrice,
            Adjustment = adjustment,
            WasCreated = wasCreated
        };
    }
}

/// <summary>What a stock transfer did, kept so it can be undone.</summary>
public sealed class StockTransferResult
{
    public required InventoryItem Source { get; init; }
    public required InventoryItem Destination { get; init; }
    public bool DestinationCreated { get; init; }
    public decimal SourceOldStock { get; init; }
    public decimal SourceOldOpeningUnits { get; init; }
    public decimal DestinationOldStock { get; init; }
    public decimal DestinationOldOpeningUnits { get; init; }
    public StockTransfer Transfer { get; set; } = null!;
    public StockAdjustment OutAdjustment { get; set; } = null!;
    public StockAdjustment InAdjustment { get; set; } = null!;
}
