using ArgoBooks.Core.Data;
using ArgoBooks.Core.Enums;
using ArgoBooks.Core.Models.Common;
using ArgoBooks.Core.Models.Entities;
using ArgoBooks.Core.Models.Inventory;
using ArgoBooks.Core.Models.Transactions;

namespace ArgoBooks.Core.Services;

/// <summary>
/// Moves stock when a purchase, sale or transfer is saved, and fixes what sold stock cost at the
/// moment of the sale. The forms and the imports all go through here so they move stock the same
/// way. See docs/Calculations.md §14.
/// </summary>
public static class InventoryStockService
{
    /// <summary>
    /// The location stock belongs to when the caller names none: the company's first location, or a
    /// real one created for it. Every stock row points at a location that exists on the Locations page.
    /// </summary>
    public static string EnsureLocationId(CompanyData data)
    {
        var existing = data.Locations.FirstOrDefault();
        if (existing != null)
            return existing.Id;

        var location = new Location { Id = new IdGenerator(data).NextLocationId(), Name = "Main" };
        data.Locations.Add(location);
        return location.Id;
    }

    /// <summary>
    /// Applies a newly saved purchase or sale to stock. Only lines whose product tracks inventory
    /// move stock.
    /// </summary>
    public static List<StockChange> Apply(
        CompanyData data, IReadOnlyList<LineItem> lines, Transaction transaction, bool isPurchase) =>
        ApplyEdit(data, [], lines, transaction, isPurchase, isPurchase ? "Expense transaction" : "Revenue transaction");

    /// <summary>
    /// Replaces what <paramref name="oldLines"/> did to stock with what <paramref name="newLines"/>
    /// do, recording one adjustment per stock record for the net change. Pass no new lines to undo a
    /// deleted transaction's stock.
    /// </summary>
    public static List<StockChange> ApplyEdit(
        CompanyData data, IReadOnlyList<LineItem> oldLines, IReadOnlyList<LineItem> newLines,
        Transaction transaction, bool isPurchase, string reason)
    {
        var touched = new List<StockChange.Builder>();
        var byItem = new Dictionary<InventoryItem, StockChange.Builder>();
        var costPriceChanged = new HashSet<Product>();

        StockChange.Builder Track(InventoryItem item, Product product, bool wasCreated)
        {
            if (!byItem.TryGetValue(item, out var builder))
            {
                builder = new StockChange.Builder(item, product, wasCreated);
                byItem[item] = builder;
                touched.Add(builder);
            }
            return builder;
        }

        // Give back what the transaction actually moved, before the new lines take anything. Its own
        // adjustments say how much: a line saved before its product tracked stock, before 2.0.6, or by
        // the spreadsheet import moved nothing, and taking its quantity back would leave stock short.
        var moved = data.StockAdjustments
            .Where(a => a.IsAutoGenerated && a.ReferenceNumber == transaction.Id)
            .GroupBy(a => a.InventoryItemId)
            .Select(g => (ItemId: g.Key, Units: g.Sum(a => a.AdjustmentType == AdjustmentType.Add ? a.Quantity : -a.Quantity)))
            .Where(m => m.Units != 0)
            .ToList();
        foreach (var (itemId, units) in moved)
        {
            var item = data.Inventory.FirstOrDefault(i => i.Id == itemId);
            var product = item == null ? null : data.GetProduct(item.ProductId);
            if (item == null || product == null) continue;

            Track(item, product, wasCreated: false);
            item.InStock -= units;
        }

        foreach (var line in oldLines.Where(l => l.OpeningUnitsUsed != 0))
        {
            var product = TrackedProduct(data, line);
            var item = product == null ? null : FindStockItem(data, product.Id, line.LocationId);
            if (item == null) continue;

            Track(item, product!, wasCreated: false);
            item.OpeningUnits += line.OpeningUnitsUsed;
        }

        var usdPerNative = UsdPerNative(transaction);
        var inCompanyCurrency = string.Equals(
            OriginalCurrency(transaction), data.Settings.Localization.Currency, StringComparison.OrdinalIgnoreCase);

        // A purchase or sale saved before cost of goods sold began was expensed, or sold at no cost, and
        // its stock is part of the opening units. Editing it moves stock as before and nothing more, or
        // that stock would come off profit twice.
        var savedBeforeCostOfGoods =
            moved.Count > 0 &&
            !oldLines.Any(l => l.IsStockPurchase || l.CostOfGoodsUSD != null);

        // An edited sale keeps the unit cost it was saved at, so a later purchase that changed the
        // stock's cost doesn't rewrite its past profit. Only a product the edit adds takes today's cost.
        var savedUnitCost = oldLines
                .Where(l => !isPurchase && l.CostOfGoodsUSD != null && l.ProductId != null && l.Quantity - l.OpeningUnitsUsed > 0)
                .GroupBy(l => (l.ProductId, l.LocationId))
                .ToDictionary(g => g.Key, g => g.Sum(l => l.CostOfGoodsUSD!.Value) / g.Sum(l => l.Quantity - l.OpeningUnitsUsed));

        foreach (var line in newLines)
        {
            line.CostOfGoodsUSD = null;
            line.OpeningUnitsUsed = 0;
            line.IsStockPurchase = false;

            var product = TrackedProduct(data, line);
            if (product == null || line.Quantity == 0) continue;

            var item = FindStockItem(data, product.Id, line.LocationId);
            var builder = item == null
                ? Track(item = CreateStockItem(data, product, line.LocationId, transaction.Date), product, wasCreated: true)
                : Track(item, product, wasCreated: false);
            line.LocationId = item.LocationId;

            if (isPurchase)
            {
                item.InStock += line.Quantity;
                if (savedBeforeCostOfGoods) continue;
                line.IsStockPurchase = true;

                if (line.Quantity > 0 && usdPerNative is { } rate)
                    item.UnitCost = line.Subtotal / line.Quantity * rate;

                if (inCompanyCurrency && costPriceChanged.Add(product))
                {
                    builder.RecordCostPrice(product);
                    product.CostPrice = line.UnitPrice;
                }
            }
            else if (savedBeforeCostOfGoods)
            {
                item.InStock -= line.Quantity;
            }
            else
            {
                var openingUsed = line.Quantity > 0 ? Math.Min(Math.Max(item.OpeningUnits, 0), line.Quantity) : 0;
                item.OpeningUnits -= openingUsed;
                line.OpeningUnitsUsed = openingUsed;
                var unitCost = savedUnitCost.TryGetValue((product.Id, item.LocationId), out var saved) ? saved : item.UnitCost;
                line.CostOfGoodsUSD = (line.Quantity - openingUsed) * unitCost;
                item.InStock -= line.Quantity;
            }
        }

        var changes = new List<StockChange>(touched.Count);
        foreach (var builder in touched)
        {
            var item = builder.Item;
            item.Status = item.CalculateStatus();
            item.LastUpdated = DateTime.UtcNow;

            var net = item.InStock - builder.OldStock;
            StockAdjustment? adjustment = null;
            if (net != 0)
            {
                adjustment = new StockAdjustment
                {
                    Id = new IdGenerator(data).NextStockAdjustmentId(),
                    InventoryItemId = item.Id,
                    AdjustmentType = net > 0 ? AdjustmentType.Add : AdjustmentType.Remove,
                    Quantity = Math.Abs(net),
                    PreviousStock = builder.OldStock,
                    NewStock = item.InStock,
                    Reason = reason,
                    ReferenceNumber = transaction.Id,
                    Timestamp = DateTime.UtcNow,
                    IsAutoGenerated = true
                };
                data.StockAdjustments.Add(adjustment);
            }

            changes.Add(builder.Build(adjustment));
        }

        return changes;
    }

    /// <summary>
    /// Puts stock back as it was before <paramref name="changes"/>: stock, opening units, unit cost and
    /// cost price restored, adjustments removed, and stock records the change created removed.
    /// </summary>
    public static void Revert(CompanyData data, IReadOnlyList<StockChange> changes)
    {
        for (var i = changes.Count - 1; i >= 0; i--)
        {
            var change = changes[i];
            var item = change.Item;
            item.InStock = change.OldStock;
            item.OpeningUnits = change.OldOpeningUnits;
            item.UnitCost = change.OldUnitCost;
            item.Status = item.CalculateStatus();
            item.LastUpdated = DateTime.UtcNow;

            if (change.CostPriceProduct != null)
                change.CostPriceProduct.CostPrice = change.OldCostPrice;

            if (change.Adjustment != null)
                data.StockAdjustments.Remove(change.Adjustment);

            if (change.WasCreated)
                data.Inventory.Remove(item);
        }
    }

    /// <summary>
    /// The stock record a line takes from or adds to: the one at the line's location when it has one,
    /// otherwise the product's first.
    /// </summary>
    public static InventoryItem? FindStockItem(CompanyData data, string productId, string? locationId)
    {
        if (!string.IsNullOrEmpty(locationId))
        {
            var atLocation = data.Inventory.FirstOrDefault(i => i.ProductId == productId && i.LocationId == locationId);
            if (atLocation != null)
                return atLocation;
        }

        return data.Inventory.FirstOrDefault(i => i.ProductId == productId);
    }

    /// <summary>Stock records for a product, one per location it is stocked at.</summary>
    public static List<InventoryItem> StockItemsFor(CompanyData data, string productId) =>
        data.Inventory.Where(i => i.ProductId == productId).ToList();

    /// <summary>
    /// Moves stock from one location to another, recording the transfer and a matching adjustment at
    /// each end. Opening units move in proportion, so the stock keeps its cost basis.
    /// </summary>
    public static StockTransferResult Transfer(
        CompanyData data, InventoryItem source, string destinationLocationId, decimal quantity, string notes)
    {
        if (quantity <= 0)
            throw new ArgumentOutOfRangeException(nameof(quantity), "A transfer moves a positive quantity.");
        if (source.LocationId == destinationLocationId)
            throw new ArgumentException("A transfer needs a different destination.", nameof(destinationLocationId));

        var product = data.GetProduct(source.ProductId);
        var destination = data.Inventory.FirstOrDefault(i =>
            i.ProductId == source.ProductId && i.LocationId == destinationLocationId);
        var destinationCreated = destination == null;
        if (destination == null)
        {
            destination = product != null
                ? CreateStockItem(data, product, destinationLocationId, DateTime.Today)
                : CreateStockItem(data, source, destinationLocationId);
            destination.UnitCost = source.UnitCost;
        }

        var result = new StockTransferResult
        {
            Source = source,
            Destination = destination,
            DestinationCreated = destinationCreated,
            SourceOldStock = source.InStock,
            SourceOldOpeningUnits = source.OpeningUnits,
            DestinationOldStock = destination.InStock,
            DestinationOldOpeningUnits = destination.OpeningUnits
        };

        var openingMoved = source.InStock > 0
            ? Math.Min(source.OpeningUnits, source.OpeningUnits * quantity / source.InStock)
            : 0;
        openingMoved = Math.Max(openingMoved, 0);

        source.InStock -= quantity;
        source.OpeningUnits -= openingMoved;
        destination.InStock += quantity;
        destination.OpeningUnits += openingMoved;

        foreach (var item in new[] { source, destination })
        {
            item.Status = item.CalculateStatus();
            item.LastUpdated = DateTime.UtcNow;
        }

        var transfer = new StockTransfer
        {
            Id = new IdGenerator(data).NextStockTransferId(),
            InventoryItemId = source.Id,
            SourceLocationId = source.LocationId,
            DestinationLocationId = destinationLocationId,
            Quantity = quantity,
            TransferDate = DateTime.Now,
            Status = TransferStatus.Completed,
            Notes = notes,
            CreatedAt = DateTime.UtcNow,
            CompletedAt = DateTime.UtcNow
        };
        data.StockTransfers.Add(transfer);

        var sourceName = data.GetLocation(source.LocationId)?.Name ?? source.LocationId;
        var destinationName = data.GetLocation(destinationLocationId)?.Name ?? destinationLocationId;

        var outAdjustment = new StockAdjustment
        {
            Id = new IdGenerator(data).NextStockAdjustmentId(),
            InventoryItemId = source.Id,
            AdjustmentType = AdjustmentType.Remove,
            Quantity = quantity,
            PreviousStock = result.SourceOldStock,
            NewStock = source.InStock,
            Reason = $"Transfer to {destinationName}",
            ReferenceNumber = transfer.Id,
            Timestamp = DateTime.UtcNow,
            IsAutoGenerated = true
        };
        data.StockAdjustments.Add(outAdjustment);

        var inAdjustment = new StockAdjustment
        {
            Id = new IdGenerator(data).NextStockAdjustmentId(),
            InventoryItemId = destination.Id,
            AdjustmentType = AdjustmentType.Add,
            Quantity = quantity,
            PreviousStock = result.DestinationOldStock,
            NewStock = destination.InStock,
            Reason = $"Transfer from {sourceName}",
            ReferenceNumber = transfer.Id,
            Timestamp = DateTime.UtcNow,
            IsAutoGenerated = true
        };
        data.StockAdjustments.Add(inAdjustment);

        result.Transfer = transfer;
        result.OutAdjustment = outAdjustment;
        result.InAdjustment = inAdjustment;
        return result;
    }

    public static void RevertTransfer(CompanyData data, StockTransferResult result)
    {
        result.Source.InStock = result.SourceOldStock;
        result.Source.OpeningUnits = result.SourceOldOpeningUnits;
        result.Destination.InStock = result.DestinationOldStock;
        result.Destination.OpeningUnits = result.DestinationOldOpeningUnits;

        foreach (var item in new[] { result.Source, result.Destination })
        {
            item.Status = item.CalculateStatus();
            item.LastUpdated = DateTime.UtcNow;
        }

        data.StockAdjustments.Remove(result.OutAdjustment);
        data.StockAdjustments.Remove(result.InAdjustment);
        data.StockTransfers.Remove(result.Transfer);

        if (result.DestinationCreated)
            data.Inventory.Remove(result.Destination);
    }

    /// <summary>
    /// USD per unit of the transaction's own currency, or null while its rate is not known yet, in
    /// which case a purchase leaves the stock's unit cost as it was.
    /// </summary>
    public static decimal? UsdPerNative(Transaction transaction) =>
        UsdPerNative(OriginalCurrency(transaction), transaction.Total, transaction.TotalUSD, transaction.IsPendingConversion);

    /// <summary><see cref="UsdPerNative(Transaction)"/> for a purchase order, whose line costs are in its own currency.</summary>
    public static decimal? UsdPerNative(PurchaseOrder order) =>
        UsdPerNative(string.IsNullOrEmpty(order.OriginalCurrency) ? "USD" : order.OriginalCurrency,
            order.Total, order.TotalUSD, order.IsPendingConversion);

    private static decimal? UsdPerNative(string currency, decimal total, decimal totalUSD, bool isPending)
    {
        if (string.Equals(currency, "USD", StringComparison.OrdinalIgnoreCase))
            return 1m;
        if (isPending || total == 0 || totalUSD == 0)
            return null;
        return totalUSD / total;
    }

    /// <summary>
    /// The product's cost price, which is in the company's currency, in USD at <paramref name="date"/>'s
    /// rate: the unit cost a new stock record starts at (docs/Calculations.md §14). 0 while that rate
    /// isn't available, just as a purchase waiting for its rate sets no cost.
    /// </summary>
    public static decimal CostPriceUSD(CompanyData data, Product product, DateTime date)
    {
        var currency = data.Settings.Localization.Currency;
        if (string.IsNullOrEmpty(currency) || string.Equals(currency, "USD", StringComparison.OrdinalIgnoreCase))
            return product.CostPrice;

        return ExchangeRateService.Instance is { } rates
               && rates.TryConvertToUsdBase(product.CostPrice, currency, date, out var usd)
            ? usd
            : 0m;
    }

    /// <summary>
    /// A new stock record for <paramref name="product"/>, added to the company, starting at the
    /// product's cost price as of <paramref name="costDate"/>.
    /// </summary>
    public static InventoryItem CreateStockItem(CompanyData data, Product product, string? locationId, DateTime costDate)
    {
        var item = NewStockItem(data, product.Id, product.Sku, locationId);
        item.UnitOfMeasure = product.UnitOfMeasure;
        item.ReorderPoint = product.ReorderPoint;
        item.OverstockThreshold = product.OverstockThreshold;
        item.UnitCost = CostPriceUSD(data, product, costDate);
        item.Status = item.CalculateStatus();
        return item;
    }

    private static string OriginalCurrency(Transaction transaction) =>
        string.IsNullOrEmpty(transaction.OriginalCurrency) ? "USD" : transaction.OriginalCurrency;

    private static Product? TrackedProduct(CompanyData data, LineItem line)
    {
        if (string.IsNullOrEmpty(line.ProductId)) return null;
        var product = data.GetProduct(line.ProductId);
        return product is { TrackInventory: true } ? product : null;
    }

    private static InventoryItem CreateStockItem(CompanyData data, InventoryItem like, string locationId)
    {
        var item = NewStockItem(data, like.ProductId, like.Sku, locationId);
        item.UnitOfMeasure = like.UnitOfMeasure;
        item.ReorderPoint = like.ReorderPoint;
        item.OverstockThreshold = like.OverstockThreshold;
        item.Status = item.CalculateStatus();
        return item;
    }

    private static InventoryItem NewStockItem(CompanyData data, string productId, string sku, string? locationId)
    {
        var item = new InventoryItem
        {
            Id = new IdGenerator(data).NextInventoryItemId(),
            ProductId = productId,
            Sku = sku,
            LocationId = !string.IsNullOrEmpty(locationId)
                ? locationId
                : EnsureLocationId(data),
            LastUpdated = DateTime.UtcNow
        };
        data.Inventory.Add(item);
        return item;
    }
}

/// <summary>What one save did to one stock record, kept so the save can be undone.</summary>
public sealed class StockChange
{
    public required InventoryItem Item { get; init; }
    public required string ProductName { get; init; }
    public decimal OldStock { get; init; }
    public decimal NewStock { get; init; }
    public decimal OldOpeningUnits { get; init; }
    public decimal OldUnitCost { get; init; }
    public Product? CostPriceProduct { get; init; }
    public decimal OldCostPrice { get; init; }
    public StockAdjustment? Adjustment { get; init; }
    public bool WasCreated { get; init; }

    internal sealed class Builder(InventoryItem item, Product product, bool wasCreated)
    {
        public InventoryItem Item { get; } = item;
        public decimal OldStock { get; } = item.InStock;
        private readonly decimal _oldOpeningUnits = item.OpeningUnits;
        private readonly decimal _oldUnitCost = item.UnitCost;
        private Product? _costPriceProduct;
        private decimal _oldCostPrice;

        public void RecordCostPrice(Product costProduct)
        {
            _costPriceProduct = costProduct;
            _oldCostPrice = costProduct.CostPrice;
        }

        public StockChange Build(StockAdjustment? adjustment) => new()
        {
            Item = Item,
            ProductName = product.Name,
            OldStock = OldStock,
            NewStock = Item.InStock,
            OldOpeningUnits = _oldOpeningUnits,
            OldUnitCost = _oldUnitCost,
            CostPriceProduct = _costPriceProduct,
            OldCostPrice = _oldCostPrice,
            Adjustment = adjustment,
            WasCreated = wasCreated
        };
    }
}

/// <summary>What a stock transfer did, kept so it can be undone.</summary>
public sealed class StockTransferResult
{
    public required InventoryItem Source { get; init; }
    public required InventoryItem Destination { get; init; }
    public bool DestinationCreated { get; init; }
    public decimal SourceOldStock { get; init; }
    public decimal SourceOldOpeningUnits { get; init; }
    public decimal DestinationOldStock { get; init; }
    public decimal DestinationOldOpeningUnits { get; init; }
    public StockTransfer Transfer { get; set; } = null!;
    public StockAdjustment OutAdjustment { get; set; } = null!;
    public StockAdjustment InAdjustment { get; set; } = null!;
}
